markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
pygments        : true
contact         : "mcburon@umich.edu"
github_url      : "https://github.com/ibug-um"
exclude         : [branding]
